### ISSUE TITLE
can I ask you the latest score you get?

### ISSUE THREAD

**Issue by zhufeng888** [zye1996/3DSSD-torch#1]
I try to reproduce 3dssd in Pytorch.but get also low scores.
can I ask you the latest mAP score you get and do you konw the evaluation meaning separately follows:
①Car AP@0.70, 0.70, 0.70:
②Car AP_R40@0.70, 0.70, 0.70:
③Car AP@0.70, 0.50, 0.50:
④Car AP_R40@0.70, 0.50, 0.50:

**Comment by zye1996** [comment]
> I try to reproduce 3dssd in Pytorch.but get also low scores.
> can I ask you the latest mAP score you get and do you konw the evaluation meaning separately follows:
> ①Car AP@0.70, 0.70, 0.70:
> ②Car AP_R40@0.70, 0.70, 0.70:
> ③Car AP@0.70, 0.50, 0.50:
> ④Car AP_R40@0.70, 0.50, 0.50:

I am getting this right now, some gradient calc problem persist and trying to fix:

```
bbox AP:88.3067, 87.4015, 87.4015
bev  AP:87.1555, 83.6703, 83.6703
3d   AP:81.8364, 75.6352, 75.6352
aos  AP:88.31, 87.40, 87.40
Car AP_R40@0.70, 0.70, 0.70:
bbox AP:92.6265, 89.2507, 89.2507
bev  AP:89.0312, 84.9429, 84.9429
3d   AP:83.2703, 74.8559, 74.8559
aos  AP:92.63, 89.25, 89.25
Car AP@0.70, 0.50, 0.50:
bbox AP:88.3067, 87.4015, 87.4015
bev  AP:88.4671, 87.8447, 87.8447
3d   AP:88.4409, 87.7542, 87.7542
aos  AP:88.31, 87.40, 87.40
Car AP_R40@0.70, 0.50, 0.50:
bbox AP:92.6265, 89.2507, 89.2507
bev  AP:92.9291, 91.6493, 91.6493
3d   AP:92.8714, 91.3892, 91.3892
aos  AP:92.63, 89.25, 89.25
```

Those are AP scores for object detection. Where R40 averages over 41 thresholds and the one without R40 averages over 11 thresholds.

**Comment by zhufeng888** [comment]
> > I try to reproduce 3dssd in Pytorch.but get also low scores.
> > can I ask you the latest mAP score you get and do you konw the evaluation meaning separately follows:
> > ①Car AP@0.70, 0.70, 0.70:
> > ②Car AP_R40@0.70, 0.70, 0.70:
> > ③Car AP@0.70, 0.50, 0.50:
> > ④Car AP_R40@0.70, 0.50, 0.50:
> 
> I am getting this right now, some gradient calc problem persist and trying to fix:
> 
> ```
> bbox AP:88.3067, 87.4015, 87.4015
> bev  AP:87.1555, 83.6703, 83.6703
> 3d   AP:81.8364, 75.6352, 75.6352
> aos  AP:88.31, 87.40, 87.40
> Car AP_R40@0.70, 0.70, 0.70:
> bbox AP:92.6265, 89.2507, 89.2507
> bev  AP:89.0312, 84.9429, 84.9429
> 3d   AP:83.2703, 74.8559, 74.8559
> aos  AP:92.63, 89.25, 89.25
> Car AP@0.70, 0.50, 0.50:
> bbox AP:88.3067, 87.4015, 87.4015
> bev  AP:88.4671, 87.8447, 87.8447
> 3d   AP:88.4409, 87.7542, 87.7542
> aos  AP:88.31, 87.40, 87.40
> Car AP_R40@0.70, 0.50, 0.50:
> bbox AP:92.6265, 89.2507, 89.2507
> bev  AP:92.9291, 91.6493, 91.6493
> 3d   AP:92.8714, 91.3892, 91.3892
> aos  AP:92.63, 89.25, 89.25
> ```
> 
> Those are AP scores for object detection. Where R40 averages over 41 thresholds and the one without R40 averages over 11 thresholds.

Thank you for your help. you have got  a great score though there is still a gap. I want to git your item to fix the bug together, and if any questions, I will feedback here.

**Comment by zhufeng888** [comment]
> > I try to reproduce 3dssd in Pytorch.but get also low scores.
> > can I ask you the latest mAP score you get and do you konw the evaluation meaning separately follows:
> > ①Car AP@0.70, 0.70, 0.70:
> > ②Car AP_R40@0.70, 0.70, 0.70:
> > ③Car AP@0.70, 0.50, 0.50:
> > ④Car AP_R40@0.70, 0.50, 0.50:
> 
> I am getting this right now, some gradient calc problem persist and trying to fix:
> 
> ```
> bbox AP:88.3067, 87.4015, 87.4015
> bev  AP:87.1555, 83.6703, 83.6703
> 3d   AP:81.8364, 75.6352, 75.6352
> aos  AP:88.31, 87.40, 87.40
> Car AP_R40@0.70, 0.70, 0.70:
> bbox AP:92.6265, 89.2507, 89.2507
> bev  AP:89.0312, 84.9429, 84.9429
> 3d   AP:83.2703, 74.8559, 74.8559
> aos  AP:92.63, 89.25, 89.25
> Car AP@0.70, 0.50, 0.50:
> bbox AP:88.3067, 87.4015, 87.4015
> bev  AP:88.4671, 87.8447, 87.8447
> 3d   AP:88.4409, 87.7542, 87.7542
> aos  AP:88.31, 87.40, 87.40
> Car AP_R40@0.70, 0.50, 0.50:
> bbox AP:92.6265, 89.2507, 89.2507
> bev  AP:92.9291, 91.6493, 91.6493
> 3d   AP:92.8714, 91.3892, 91.3892
> aos  AP:92.63, 89.25, 89.25
> ```
> 
> Those are AP scores for object detection. Where R40 averages over 41 thresholds and the one without R40 averages over 11 thresholds.

Does the released item not give us the latest result,  there are some issues when running?

**Comment by zye1996** [comment]
It should give you the latest result though I am still looking for a solution to get higher performance
