### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by qiqihaer** [zye1996/3DSSD-torch#2]
Thanks for finding the bugs on the original version. Can you send me an e-mail to establish a better communication? My e-mail address is 11732011@.zju.edu.cn

**Comment by zye1996** [comment]
Hi I have sent you the email

**Comment by qiqihaer** [comment]
I am sorry, the email I left is wrong, since I add a dot after the @. I have not received the email. Could you please send me another email? 11732011@zju.edu.cn

**Comment by zye1996** [comment]
> I am sorry, the email I left is wrong, since I add a dot after the @. I have not received the email. Could you please send me another email? 11732011@zju.edu.cn

Sure I sent another
