### ISSUE TITLE
KITTI DATA

### ISSUE THREAD

**Issue by RolandoAvides** [zye1996/3DSSD-torch#4]
Hi!

Regarding the the data folder, should it follow the proposed organization of MMDetection3D and OpenPCDet?

Thanks in advance!

**Comment by zye1996** [comment]
The folder structure follows opecpcdet> Hi!
> 
> 
> 
> Regarding the the data folder, should it follow the proposed organization of MMDetection3D and OpenPCDet?
> 
> 
> 
> Thanks in advance!
