### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by RolandoAvides** [zye1996/3DSSD-torch#6]
Hi!

I followed the configurations steps 1 - 3 and then tried the command for the pre-trained model.

I got this error:

AttributeError: module 'spconv' has no attribute 'SparseModule'

Do you know what this means? I have already installed sparse convolutions.

Thanks!

**Comment by zye1996** [comment]
mostly because you did not install the spconv package correctly, the implementation did not use spconv for modeling

**Comment by RolandoAvides** [comment]
But I followed the Sparse Convolution instructions.

Could it be about the folders?

**Comment by zye1996** [comment]
how about deleting the spconv folder under ops?

**Comment by zye1996** [comment]
did you install spconv after running ```python setup.py develop```? Otherwise you need to install in reversed order, i.e., install spconv first

**Comment by RolandoAvides** [comment]
Hi there! 

I tried to delete the spconv folder under ops, but it didn't solve the problem.

I tried to reinstall the sparse convolutions, but I am having some issues regarding the final configuration step:

 - Run cd ./dist, use pip to install the generated whl file.

I have a spcov folder in 3DSSD-torch folder, and also another spconv folder inside spconv folder.

Thanks in advance!

**Comment by zye1996** [comment]
> Hi there! 
> 
> 
> 
> I tried to delete the spconv folder under ops, but it didn't solve the problem.
> 
> 
> 
> I tried to reinstall the sparse convolutions, but I am having some issues regarding the final configuration step:
> 
> 
> 
>  - Run cd ./dist, use pip to install the generated whl file.
> 
> 
> 
> I have a spcov folder in 3DSSD-torch folder, and also another spconv folder inside spconv folder.
> 
> 
> 
> Thanks in advance!
> 
> 

I don't quite understand your problem. What is your error code for the step?

**Comment by RolandoAvides** [comment]
When i run the step 3 command of this rep: python setup.py 
I get this final message: 
 - No local packages or working download links found for spconv
   error: Could not find suitable distribution for Requirement.parse('spconv')

However, I was now looking at the terminal and I think it is already installed. 

I will try to use the pre-trained model and check for possible errors. Maybe there is no error at all.

Thanks in advance!

**Comment by RolandoAvides** [comment]
I ran the python test.py --cfg_file cfgs/kitti_models/3dssd.yaml --ckpt ../output/kitti_models/3dssd/default/ckpt/checkpoint_epoch_120.pth command and got this error:

AttributeError: module 'spconv' has no attribute 'SparseModule'

**Comment by zye1996** [comment]
> I ran the python test.py --cfg_file cfgs/kitti_models/3dssd.yaml --ckpt ../output/kitti_models/3dssd/default/ckpt/checkpoint_epoch_120.pth command and got this error:
> 
> 
> 
> AttributeError: module 'spconv' has no attribute 'SparseModule'
> 
> 
I double checked the procedure and I had no issues at all. It should be the problem with your setup environment. Make sure you are install spconv using the pip tool in the same conda environment

**Comment by RolandoAvides** [comment]
I'll try to install spconv again. Should it be installed inside 3DSSD-torch folder?

I was looking at the spconv installation steps, but iḿ not understanding this step in their repo:

2. Download cmake >= 3.13.2, then add cmake executables to PATH

What do they mean by saying "add cmake executables to PATH"?
