### ISSUE TITLE
Training block

### ISSUE THREAD

**Issue by pigtigger** [zye1996/3DSSD-torch#9]
![image](https://user-images.githubusercontent.com/39974202/144200202-785977c9-1844-4346-842d-ec8034b46410.png
Anybody knows how much time should this step(Wait xxx check xx) consume? I have been blocked by this for almost one hour. :(

**Comment by pigtigger** [comment]
![image](https://user-images.githubusercontent.com/39974202/144205416-95cb6163-206c-4541-a7fd-407fed753fb8.png)
The problem is caused by the code to load ckpt,  this line loads a 120 epoch pth by default and will not be train because of total epochs is set to 120 in cfg.

**Comment by zye1996** [comment]
> ![image](https://user-images.githubusercontent.com/39974202/144205416-95cb6163-206c-4541-a7fd-407fed753fb8.png)
> The problem is caused by the code to load ckpt, this line loads a 120 epoch pth by default and will not be train because of total epochs is set to 120 in cfg.

This is by default the design of OpenPCDet and not a bug.
